/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ItemController;
import Controller.posController;
import Model.Item;
import Model.PosDAO;
import Model.Transaction;
import Model.TransactionItem;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;

/**
 *
 * @author ravin
 */ 
public class POS_System extends javax.swing.JFrame {

    /**
     * Creates new form POS_System
     */
  
    private JFrame previousForm;
    
      public POS_System(JFrame previousForm) {
        initComponents();
        this.previousForm = previousForm;
    }
    public POS_System() {
        initComponents();
    startClock();
        quantityspinner.setValue(1);
        loadTableDataAsync();
           this.setExtendedState(POS_System.MAXIMIZED_BOTH); // Maximize window
        this.setVisible(true);
         searchKey();
         addtocarttabler();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        txtcategory = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtvolumns = new javax.swing.JTextField();
        txtItemCode = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtUnitPrice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addtocarttable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        hh = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        totgrand = new javax.swing.JLabel();
        totdiscount = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        postable = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        txtVehicle = new javax.swing.JTextField();
        txtVolumn = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        clr_button = new javax.swing.JButton();
        quantityspinner = new javax.swing.JSpinner();
        deletecartrow = new javax.swing.JButton();
        lbeldis = new javax.swing.JLabel();
        txtdiscount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        lbldate = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtvehicletype = new javax.swing.JTextField();
        orderID = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cashierid = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Unit Price");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Category");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Product Name");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Product Code");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Quantity");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Volumn");

        txtItemCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemCodeActionPerformed(evt);
            }
        });

        jButton1.setText("Add to Cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        addtocarttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Item Name", "Category", "Item Price", "Quantity", "Price", "Discount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(addtocarttable);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setText("Total");

        hh.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        hh.setText("Discount");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel8.setText("Grand Total");

        totgrand.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        totgrand.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totgrand.setText("000");

        totdiscount.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        totdiscount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totdiscount.setText("000");

        lbl_total.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lbl_total.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_total.setText("000");
        lbl_total.setToolTipText("");
        lbl_total.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lbl_total.setVerifyInputWhenFocusTarget(false);

        jButton3.setText("Cancel Order");

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        postable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane2.setViewportView(postable);

        txtVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Brand");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Vehicle Type");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Volumn");

        clr_button.setText("Clear Filter");
        clr_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clr_buttonActionPerformed(evt);
            }
        });

        deletecartrow.setBackground(new java.awt.Color(255, 51, 51));
        deletecartrow.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deletecartrow.setForeground(new java.awt.Color(255, 255, 255));
        deletecartrow.setText("-");
        deletecartrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletecartrowActionPerformed(evt);
            }
        });

        lbeldis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbeldis.setText("Discount");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Additional Discount Rate %");

        jButton4.setText("Apply Discount");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "5", "10", "15", "20" }));

        lbldate.setBackground(new java.awt.Color(255, 255, 255));
        lbldate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbldate.setForeground(new java.awt.Color(0, 153, 51));
        lbldate.setText("jLabel9");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Vehicle Type");

        orderID.setText("jLabel10");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Order No: ");

        jLabel12.setText("Cashier ID");

        cashierid.setText("1");

        btnBack.setText("<-");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(74, 74, 74))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(86, 86, 86)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(74, 74, 74)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel20)
                        .addGap(0, 776, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(txtVolumn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(clr_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 474, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(orderID, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(lbldate, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(cashierid, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(45, 45, 45)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtItemCode, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                .addComponent(txtItemName)
                                .addComponent(txtcategory)
                                .addComponent(txtUnitPrice))
                            .addGap(83, 83, 83)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lbeldis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(42, 42, 42)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(quantityspinner, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                        .addComponent(txtvolumns)
                                        .addComponent(txtdiscount)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtvehicletype)))
                            .addGap(38, 38, 38)
                            .addComponent(jButton1)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton3)
                            .addGap(52, 52, 52)
                            .addComponent(jButton2)
                            .addGap(18, 18, 18)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(jButton4))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hh, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_total, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(totdiscount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totgrand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deletecartrow, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(orderID)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBack)
                                    .addComponent(lbldate))))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(cashierid))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(36, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVolumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clr_button))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18))
                        .addGap(15, 15, 15)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1)
                                        .addComponent(txtvolumns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(quantityspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbeldis)
                                    .addComponent(txtdiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtvehicletype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(deletecartrow)))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lbl_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hh)
                            .addComponent(totdiscount)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(totgrand))
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(64, 64, 64))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void startClock() {
    javax.swing.Timer timer = new javax.swing.Timer(1000, e -> {
        LocalDateTime now = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        lbldate.setText(now.format(formatter));
        int nextOrderId = new PosDAO().getOrderId();
        orderID.setText(String.valueOf(nextOrderId));
    });
    timer.start();
}


     private void loadTableDataAsync() {
    SwingWorker<List<Item>, Void> worker = new SwingWorker<>() {
        @Override
        protected List<Item> doInBackground() throws Exception {
            // Background thread: fetch items from DB
            return ItemController.getAllItems();
        }

        @Override
        protected void done() {
            try {
                List<Item> items = get();

                // Define your table columns
                String[] columnNames = {
                    "Item Code", "Item Name", "Brand", "Category", "Vehicle Type",
                  "Volume", "Unit",
                    "Package Type",
                    "Selling Price", "Discount", "Stock Qty"
                };

                // Create a read-only model
                DefaultTableModel model = new DefaultTableModel(columnNames, 0) {
                    @Override
                    public boolean isCellEditable(int row, int column) {
                      return row == getRowCount() - 1; // only the last row editable
                    }
                };

                // Assign model to the table
                postable.setModel(model);

                // Fill rows
                for (Item item : items) {
                    Object[] row = new Object[] {
                        item.getItemCode(),
                        item.getItemName(),
                        item.getBrand(),
                        item.getCategory(),
                        item.getVehicleType(),                
                        item.getVolumn(),
                        item.getUnit(),
                        item.getPackageType(),
                        item.getSellingPrice(),
                        item.getDiscount(),
                        item.getStockQty(),
                      
                    };
                    model.addRow(row);
                }
                
                postable.setModel(model);
                
                postable.addMouseListener(new java.awt.event.MouseAdapter(){
                    
                    public void mouseClicked(java.awt.event.MouseEvent evt){
                        int selectedRow = postable.getSelectedRow();
                        if(selectedRow != -1){
                             txtItemCode.setText(postable.getValueAt(selectedRow, 0).toString());
                            txtItemName.setText(postable.getValueAt(selectedRow, 1).toString());
                            txtcategory.setText(postable.getValueAt(selectedRow, 3).toString());
                            txtUnitPrice.setText(postable.getValueAt(selectedRow, 8).toString());
                           txtvolumns.setText(postable.getValueAt(selectedRow, 5).toString());
                           txtdiscount.setText(postable.getValueAt(selectedRow, 9).toString());
                           txtvehicletype.setText(postable.getValueAt(selectedRow, 4).toString());
                        }
                        
                    }
                });

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Failed to load data: " + e.getMessage());
            }
        }
    };

    worker.execute();
}
     private void filterItems() {
    String itemName = txtSearch.getText().trim();
    String brand = txtVehicle.getText().trim();
    String category = txtVolumn.getText().trim();

    List<Item> filteredItems = ItemController.searchItems(itemName, brand, category);
    populateTable(filteredItems);
}
  /*------------------------------------------------------------*/
private void searchKey()
{
          KeyAdapter searchKeyListener = new KeyAdapter() {
    @Override
    public void keyReleased(KeyEvent e) {
        filterItems();
    }
  

};
          txtSearch.addKeyListener(searchKeyListener);
txtVehicle.addKeyListener(searchKeyListener);
txtVolumn.addKeyListener(searchKeyListener); 
}
private void populateTable(List<Item> items) {
    DefaultTableModel model = (DefaultTableModel) postable.getModel();
    model.setRowCount(0); // clear existing rows

    for (Item item : items) {
        model.addRow(new Object[] {
            item.getItemCode(),
            item.getItemName(),
            item.getBrand(),
            item.getCategory(),
            item.getVehicleType(),
            item.getViscosityGrade(),
            item.getApiStandard(),
            item.getVolumn(),
            item.getUnit(),
            item.getPackageType(),
            item.getBatchNo(),
            item.getExpiryDate(),
            item.getCostPrice(),
            item.getSellingPrice(),
            item.getDiscount(),
            item.getStockQty(),
            item.getSupplier()
        });
    }
}
    
    
    private void txtItemCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemCodeActionPerformed

    private void txtVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleActionPerformed

    private void clr_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clr_buttonActionPerformed
         txtSearch.setText("");
    txtVehicle.setText("");
    txtVolumn.setText("");
   loadTableDataAsync();
    }//GEN-LAST:event_clr_buttonActionPerformed
private void addtocarttabler(){
    DefaultTableModel modelX = new DefaultTableModel(
    new Object[]{"Item Code", "Item Name", "Category","vehicle Type", "Unit Price", "Quantity", "Total", "Discount"}, 0
) {
    @Override
    public boolean isCellEditable(int row, int column) {
        return false; // all cells are read-only
    }
};

// Assign the model to your table
addtocarttable.setModel(modelX);
}

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        // Get the table model
        DefaultTableModel modelX = (DefaultTableModel) addtocarttable.getModel();
  // Read values from text fields
        String itemCode = txtItemCode.getText();
        String itemName = txtItemName.getText();
        String category = txtcategory.getText();
        double unitPrice = Double.parseDouble(txtUnitPrice.getText());
         double discount = Double.parseDouble(txtdiscount.getText());
        String volume = txtvolumns.getText();
        int value = (int) quantityspinner.getValue();
        String vehicleType = txtvehicletype.getText();

        // Assign (add) them to x table
        modelX.addRow(new Object[]{
            itemCode,
            itemName,
            category,
            vehicleType,
            unitPrice,
            value,
            unitPrice * value,
            discount * value,
        });

        // Optional: Clear text fields after assigning
        txtItemCode.setText("");
        txtItemName.setText("");
        txtcategory.setText("");
        txtUnitPrice.setText("");
        txtvolumns.setText("");
        txtdiscount.setText("");
        txtvehicletype.setText("");
        
     double totalSum = 0;
    double totaldiscount = 0;
    
    for (int i = 0; i < modelX.getRowCount(); i++) {
        Object valueObj = modelX.getValueAt(i, 6); 
         Object valueObjj = modelX.getValueAt(i, 7);
        if (valueObj != null || valueObjj != null) {
            totalSum += Double.parseDouble(valueObj.toString());
            totaldiscount += Double.parseDouble(valueObjj.toString());
        }
    }
    

    // Assign sum to label
    lbl_total.setText(String.format("%.2f", totalSum));
    totdiscount.setText(String.format("%.2f",  totaldiscount));
    totgrand.setText(String.format("%.2f",  totalSum-totaldiscount));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deletecartrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletecartrowActionPerformed
       int selectedRow = addtocarttable.getSelectedRow();

    if (selectedRow != -1) { // -1 means no row is selected
        // Remove the selected row from the table model
        DefaultTableModel model = (DefaultTableModel) addtocarttable.getModel();
        model.removeRow(selectedRow);
    } else {
        // Optional: show a message if no row is selected
        JOptionPane.showMessageDialog(this, "Please select a row to delete!");
    }
      DefaultTableModel modelX = (DefaultTableModel) addtocarttable.getModel();
    double totalSum = 0;
    double totaldiscount = 0;
    for (int i = 0; i < modelX.getRowCount(); i++) {
        Object valueObj = modelX.getValueAt(i, 7); // column index 5 = Total
         Object valueObjj = modelX.getValueAt(i, 8);
        if (valueObj != null || valueObjj != null) {
            totalSum += Double.parseDouble(valueObj.toString());
            totaldiscount += Double.parseDouble(valueObjj.toString());
        }
    }

    // Update the label
    lbl_total.setText(String.format("%.2f", totalSum));
    totdiscount.setText(String.format("%.2f",  totaldiscount));
      totgrand.setText(String.format("%.2f",  totalSum-totaldiscount));
    }//GEN-LAST:event_deletecartrowActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         DefaultTableModel modelX = (DefaultTableModel) addtocarttable.getModel();
    double totalSum = 0;
    double totaldiscount = 0;
     int discountPercent = Integer.parseInt(jComboBox1.getSelectedItem().toString());
    for (int i = 0; i < modelX.getRowCount(); i++) {
        Object valueObj = modelX.getValueAt(i, 6); // column index 5 = Total
         Object valueObjj = modelX.getValueAt(i, 7);
        if (valueObj != null || valueObjj != null) {
            totalSum += Double.parseDouble(valueObj.toString());
            totaldiscount += Double.parseDouble(valueObjj.toString());
        }
    }
    double finaldis = 0;
    finaldis = totaldiscount+ (totaldiscount*discountPercent/100);

    // Update the label
    lbl_total.setText(String.format("%.2f", totalSum));
    totdiscount.setText(String.format("%.2f", finaldis ));
      totgrand.setText(String.format("%.2f",  totalSum-finaldis));
    }//GEN-LAST:event_jButton4ActionPerformed
//===========================================================================================================
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

DefaultTableModel model = (DefaultTableModel) addtocarttable.getModel();
posController.insertFullTransaction(
        lbldate.getText(),
        cashierid.getText(),
        totgrand.getText(),
        totdiscount.getText(),
        model
);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       this.setVisible(false);      // hide current form
    if (previousForm != null) {
        previousForm.setVisible(true); // show previous
    }
    }//GEN-LAST:event_btnBackActionPerformed
//============================================================================================================
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POS_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POS_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POS_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POS_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POS_System().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable addtocarttable;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel cashierid;
    private javax.swing.JButton clr_button;
    private javax.swing.JButton deletecartrow;
    private javax.swing.JLabel hh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbeldis;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel orderID;
    private javax.swing.JTable postable;
    private javax.swing.JSpinner quantityspinner;
    private javax.swing.JLabel totdiscount;
    private javax.swing.JLabel totgrand;
    private javax.swing.JTextField txtItemCode;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtUnitPrice;
    private javax.swing.JTextField txtVehicle;
    private javax.swing.JTextField txtVolumn;
    private javax.swing.JTextField txtcategory;
    private javax.swing.JTextField txtdiscount;
    private javax.swing.JTextField txtvehicletype;
    private javax.swing.JTextField txtvolumns;
    // End of variables declaration//GEN-END:variables
}
